title: Nikolay Sevastyanov
logo: images/circular_image.png
description: Аналитик данных с коммерческим опытом 1 год, сэкономил компаниям более 7 млн. тг в год благодаря своим проектам.
#show_downloads: true
theme: jekyll-theme-minimal
